openapi: 3.0.0
info:
  title: Media API
  description: API za upravljanje seznama filmov in serij
  version: "1.0.0"

servers:
  - url: http://localhost:5000

paths:
  /media:
    get:
      summary: Pridobi vse medije
      responses:
        "200":
          description: Seznam medijev
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Media"

    post:
      summary: Dodaj nov medij
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/MediaInput"
      responses:
        "201":
          description: Medij uspešno dodan
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Media added

  /media/{id}:
    put:
      summary: Posodobi medij
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/MediaUpdate"
      responses:
        "200":
          description: Medij posodobljen
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Media updated

    delete:
      summary: Izbriši medij
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Medij izbrisan
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Media deleted

components:
  schemas:
    Media:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        type:
          type: string
          enum: [film, series]
        status:
          type: string
          enum: [planned, watching, completed]
        rating:
          type: integer
          nullable: true

    MediaInput:
      type: object
      required:
        - title
        - type
      properties:
        title:
          type: string
        type:
          type: string
          enum: [film, series]
        status:
          type: string
          enum: [planned, watching, completed]
        rating:
          type: integer

    MediaUpdate:
      type: object
      properties:
        status:
          type: string
          enum: [planned, watching, completed]
        rating:
          type: integer
